module.exports = {
    apps: [
        {
            name: 'unieval-api',
            script: 'server.ts',
            interpreter: 'npx',
            interpreter_args: 'tsx',
            instances: 1,
            exec_mode: 'fork',
            env_production: { NODE_ENV: 'production', PORT: 3000 },
            max_memory_restart: '500M',
            wait_ready: true,
            listen_timeout: 10000,
            kill_timeout: 5000,
            out_file: './logs/api-out.log',
            error_file: './logs/api-error.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            merge_logs: true,
        },
        {
            name: 'unieval-worker',
            script: 'worker.ts',
            interpreter: 'npx',
            interpreter_args: 'tsx',
            instances: 1,
            exec_mode: 'fork',
            env_production: { NODE_ENV: 'production' },
            max_memory_restart: '400M',
            out_file: './logs/worker-out.log',
            error_file: './logs/worker-error.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
    ],
};
